const stickerImageMapping = {
    "New York de Spidey": {
      "NY, Mon Pote !": "NewYorkSpidey_NYMonPote.jpg",
      "Qui Suis-Je ?": "NewYorkSpidey_Quisuisje.jpg",
      "Metro en Retard": "NewYorkSpidey_Metroenretard.jpg",
      "Transport Aérien": "NewYorkSpidey_Transportaerien.jpg",
      "Hot-Dog Mythique": "NewYorkSpidey_HotDogMythique.jpg",
      "Sens de Spidey": "NewYorkSpidey_SensdeSpidey.jpg",
      "Pigeon Voleur": "NewYorkSpidey_Pigeonvoleur.jpg",
      "Sauver le Chaton": "NewYorkSpidey_Sauverlechaton.jpg",
      "Quelle journée !": "NewYorkSpidey_Quellejournee.jpg",
    },
    "Salut les musclés": {
      "Appel d'Urgence": "SalutLesMuscles_AppelUrgence.jpg",
      "Un Bon Plan": "SalutLesMuscles_UnBonPlan.jpg",
      "Hulk-Dozer": "SalutLesMuscles_HulkDozer.jpg",
      "Haute Tension": "SalutLesMuscles_HauteTension.jpg",
      "Plombier Pro": "SalutLesMuscles_PlombierPro.jpg",
      "Bien Tenté": "SalutLesMuscles_BienTenté.jpg",
      "Un Peu de Jus": "SalutLesMuscles_UnPeuDeJus.jpg",
      "Au Top": "SalutLesMuscles_AuTop.jpg",
      "Héros Locaux": "SalutLesMuscles_HerosLocaux.jpg",
    },
    "Cosmo et Scottie": {
      "Atterrissage": "CosmoScottie_Atterrissage.jpg",
      "Voici Cosmo !": "CosmoScottie_VoiciCosmo.jpg",
      "Ecureuil !": "CosmoScottie_Ecureuil.jpg",
      "Vol Chercher !": "CosmoScottie_VolChercher.jpg",
      "Jetpack": "CosmoScottie_Jetpack.jpg",
      "Visiter la Maison": "CosmoScottie_VisiterMaison.jpg",
      "Rocket Chic": "CosmoScottie_RocketChic.jpg",
      "Quelle aventure": "CosmoScottie_QuelleAventure.jpg",
      "Gardien Honoraire": "CosmoScottie_GardienHonoraire.jpg",
    },
    "Potes de Gym": {
      "Nouvelle Routine": "PotesDeGym_NouvelleRoutine.jpg",
      "Objectifs de Force": "PotesDeGym_ObjectifsForce.jpg",
      "Le Meilleur Coach": "PotesDeGym_MeilleurCoach.jpg",
      "Impressionné": "PotesDeGym_Impressionne.jpg",
      "Pause du Guerrier": "PotesDeGym_PoseGuerrier.jpg",
      "Près du But": "PotesDeGym_PresDuBut.jpg",
      "Entrainement Ecourté": "PotesDeGym_EntrainementEcourte.jpg",
      "Des Muscles !": "PotesDeGym_DesMuscles.jpg",
      "Skå !": "PotesDeGym_Ska.jpg",
    },
    "Tisseur de toile": {
      "Tenue Tonique": "TisseurDeToile_TenueTonique.jpg",
      "Miles et Cynthia": "TisseurDeToile_MilesEtCynthia.jpg",
      "Dessins de Spidey": "TisseurDeToile_DessinDeSpidey.jpg",
      "Pièce Secrète": "TisseurDeToile_PieceSecrete.jpg",
      "Super-Costumes": "TisseurDeToile_SuperCostumes.jpg",
      "Captain M": "TisseurDeToile_CaptainM.jpg",
      "Tisseuse de Toile": "TisseurDeToile_TisseuseDeToile.jpg",
      "Finitions": "TisseurDeToile_Finitions.jpg",
      "Miles au Sommet": "TisseurDeToile_MilesAuSommet.jpg",
    },
    "Double Deadpool": {
      "Furtif Pool": "DoubleDeadpool_Furtifpool.jpg",
      "Vol de Chapeau": "DoubleDeadpool_VolDeChapeau.jpg",
      "Monopoly en Folie": "DoubleDeadpool_MonopolyEnFolie.jpg",
      "Oeuvre d'Art": "DoubleDeadpool_OeuvreArt.jpg",
      "Partager les Richesses": "DoubleDeadpool_PartagerRichesses.jpg",
      "Chimichangas !": "DoubleDeadpool_Chimichangas.jpg",
      "Courtier Courtisé": "DoubleDeadpool_CourtierCourtise.jpg",
      "Qui ? Moi ?": "DoubleDeadpool_QuiMoi.jpg",
      "A Plus dans le Bus !": "DoubleDeadpool_APlusDansLeBus.jpg",
    },
    "Golfeuse Verte": {
      "Tous au Green": "GolfeuseVerte_TousAuGreen.jpg",
      "Chauffeur XXL": "GolfeuseVerte_ChauffeurXXL.jpg",
      "Club Sandwich": "GolfeuseVerte_ClubSandwich.jpg",
      "Main de Hulk": "GolfeuseVerte_MainHulk.jpg",
      "Quel Danger ?": "GolfeuseVerte_QuelDanger.jpg",
      "QUEL COUP !": "GolfeuseVerte_QuelCoup.jpg",
      "Oups": "GolfeuseVerte_Oups.jpg",
      "Jour de Banner": "GolfeuseVerte_JourDeBanner.jpg",
      "Fête sur le Green": "GolfeuseVerte_FeteSurLeGreen.jpg",
    },
    "Ecole Shield": {
      "Nick Fury": "EcoleShield_NickFury.jpg",
      "QG du SHIELD": "EcoleShield_QGduShield.jpg",
      "Gloire au SHIELD": "EcoleShield_GloireAuShield.jpg",
      "Oeil de Magnat": "EcoleShield_OeilDeMagnat.jpg",
      "Sans Faute": "EcoleShield_SansFaute.jpg",
      "Coup d'Envoi": "EcoleShield_CoupEnvoi.jpg",
      "Duel des Agents": "EcoleShield_DuelDesAgents.jpg",
      "Nouveau Membre": "EcoleShield_NouveauMembre.jpg",
      "Badge d'Honneur": "EcoleShield_BadgeHonneur.jpg",
    },
    "Bouffon Vert": {
      "Piles": "BouffonVert_Piles.jpg",
      "Vol de Tartes": "BouffonVert_VolDeTartes.jpg",
      "Ça alors !": "BouffonVert_CaAlors.jpg",
      "Frondeur de Toile": "BouffonVert_FrondeurDeToile.jpg",
      "Repaire Secret": "BouffonVert_RepereSecret.jpg",
      "Bouffon Affamé": "BouffonVert_BouffonAffame.jpg",
      "Du Dessus": "BouffonVert_DuDessus.jpg",
      "Ligoté": "BouffonVert_Ligote.jpg",
      "Livraison Spéciale": "BouffonVert_LivraisonSpeciale.jpg",
    },
    "Monopoly Avengers": {
      "Arrivée des Héros": "MonopolyAvengers_ArriveeDesHeros.jpg",
      "On s'ennuie": "MonopolyAvengers_OnSennuie.jpg",
      "Super Affaire !": "MonopolyAvengers_SuperAffaire.jpg",
      "Mjolnir Tout Neuf": "MonopolyAvengers_MjolnirToutNeuf.jpg",
      "Mini Hulk": "MonopolyAvengers_MiniHulk.jpg",
      "Micropoly": "MonopolyAvengers_Micropoly.jpg",
      "Iron Man": "MonopolyAvengers_IronMan.jpg",
      "Fine Guêpe": "MonopolyAvengers_FineGuepe.jpg",
      "Rassemblement !": "MonopolyAvengers_Rassemblement.jpg",
    },
    "Le Braquage": {
      "Patrouille": "LeBraquage_Patrouille.jpg",
      "Le Braquage": "LeBraquage_LeBraquage.jpg",
      "Mystique": "LeBraquage_Mystique.jpg",
      "L'Heure du Leurre": "LeBraquage_LHeureDuLeurre.jpg",
      "Lévitation": "LeBraquage_Levitation.jpg",
      "Enfant Prodige": "LeBraquage_EnfantProdige.jpg",
      "Fait pour un Roi": "LeBraquage_FaitPourUnRoi.jpg",
      "Impossible !": "LeBraquage_Impossible.jpg",
      "Sans Accroc": "LeBraquage_SansAccroc.jpg",
    },
    "Avant le braquage": {
      "Au Voleur !": "AvantLeBraquage_AuVoleur.jpg",
      "Interpellation": "AvantLeBraquage_Interpellation.jpg",
      "Apprends-Moi": "AvantLeBraquage_ApprendsMoi.jpg",
      "Formation d'Espion": "AvantLeBraquage_FormationEspion.jpg",
      "Gadgets": "AvantLeBraquage_Gadgets.jpg",
      "Exercices": "AvantLeBraquage_Exercices.jpg",
      "Force de Frappe": "AvantLeBraquage_ForceDeFrappe.jpg",
      "Alerte au Braquage": "AvantLeBraquage_AlerteAuBraquage.jpg",
      "Main dans le Sac": "AvantLeBraquage_MainDansLeSac.jpg",
    },
    "Détective Jones": {
      "Nocturne": "DetectiveJones_Nocturne.jpg",
      "Disparition": "DetectiveJones_Disparition.jpg",
      "Un Nouveau Cas": "DetectiveJones_UnNouveauCas.jpg",
      "Qui est Coupable ?": "DetectiveJones_QuiEstCoupable.jpg",
      "Chercher l'Indice": "DetectiveJones_ChercherIndice.jpg",
      "Suspects Habituels": "DetectiveJones_SuspectsHabituels.jpg",
      "Innocent ?": "DetectiveJones_Innocent.jpg",
      "Patte Parlante": "DetectiveJones_PatteParlante.jpg",
      "Tu es Fait !": "DetectiveJones_TuEsFait.jpg",
    },
    "Wade et Logan": {
      "Wade s'amuse": "WadeEtLogan_WadeSamuse.jpg",
      "Triste Pool": "WadeEtLogan_Tristepool.jpg",
      "Doppool-Ganger": "WadeEtLogan_DoppoolGanger.jpg",
      "X-Manucure": "WadeEtLogan_XManucure.jpg",
      "Waferine": "WadeEtLogan_Waferine.jpg",
      "Si Seulement": "WadeEtLogan_SiSeulement.jpg",
      "Rêves Fous": "WadeEtLogan_RevesFous.jpg",
      "Examen Artistique": "WadeEtLogan_ExamenArtistique.jpg",
      "Meilleurs Amis": "WadeEtLogan_MeilleursAmis.jpg",
    },
    "Héros planètaires": {
      "Equipe de Nettoyage": "HerosPlanetaire_EquipeNettoyage.jpg",
      "Longue Portée": "HerosPlanetaire_LonguePortee.jpg",
      "Tornade de Dêchets": "HerosPlanetaire_TornadeDeDechets.jpg",
      "Black Panther": "HerosPlanetaire_BlackPanther.jpg",
      "Racines de Groot": "HerosPlanetaire_RacinesDeGroot.jpg",
      "Morcepool": "HerosPlanetaire_Morsepool.jpg",
      "Jeter les ordures": "HerosPlanetaire_JeterLesOrdures.jpg",
      "Nettoyer les Cieux": "HerosPlanetaire_NettoyerLesCieux.jpg",
      "Galactus": "HerosPlanetaire_Galactus.jpg",
    },
    "Style Wakanda": {
      "Wakanda !": "StyleWakanda_Wakanda.jpg",
      "Labo de Shury": "StyleWakanda_LaboDeShuri.jpg",
      "Technologie Avancée": "StyleWakanda_TechnologieAvancee.jpg",
      "Chat Numérique": "StyleWakanda_ChatNumerique.jpg",
      "Next Gen": "StyleWakanda_NextGen.jpg",
      "Style Vibranium": "StyleWakanda_StyleVibranium.jpg",
      "Salut des Savants": "StyleWakanda_SalutDesSavants.jpg",
      "Nouveaux Jouets": "StyleWakanda_NouveauxJouets.jpg",
      "En Costume": "StyleWakanda_EnCostume.jpg",
    },
    "Manoir X": {
      "Le Commencement": "ManoirX_LeCommencement.jpg",
      "Top Secret": "ManoirX_TopSecret.jpg",
      "Amis de la Science": "ManoirX_AmisDeLaScience.jpg",
      "Le Dernier Debout": "ManoirX_LeDernierDebout.jpg",
      "M Cerebro": "ManoirX_MCerebro.jpg",
      "Coup de Vent": "ManoirX_CoupDeVent.jpg",
      "Super-Viseur": "ManoirX_SuperViseur.jpg",
      "Malicia la Malice": "ManoirX_MaliciaLaMalice.jpg",
      "Dernier Gambit": "ManoirX_DernierGambit.jpg",
    },
    "Etrange Strange": {
        "Un Bon Comique": "EtrangeStrange_UnBonComic.jpg",
        "Gros Bouton Rouge": "EtrangeStrange_GrosBoutonRouge.jpg",
        "ZAP !": "EtrangeStrange_ZAP.jpg",
        "Le Coup de la Cape": "EtrangeStrange_LeCoupDeLaCape.jpg",
        "Docteur Strange": "EtrangeStrange_DrStrange.jpg",
        "Orbe d'Agamotto": "EtrangeStrange_OrbeDAgamotto.jpg",
        "Gargantos": "EtrangeStrange_Gargantos.jpg",
        "Portail de Retour": "EtrangeStrange_PortailDeRetour.jpg",
        "Tout est Normal": "EtrangeStrange_ToutEstNormal.jpg",
    }
  };

  module.exports = stickerImageMapping;